apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjsbuildpack
  namespace: nextjsbuildpack
  labels:
    app: nextjsbuildpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjsbuildpack
  template:
    metadata:
      labels:
        app: nextjsbuildpack
    spec:
      containers:
        - name: nextjsbuildpack
          image: ghcr.io/imohiosen/nextjsbuildpack:latest
          ports:
            - containerPort: 3000
          command: ["npm", "run", "start:prod"]
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
      imagePullSecrets:
        - name: ghcr-login-secret
