name: CI/CD with Buildpacks and Kubernetes

on:
  push:
    branches:
      - main  # Adjust based on your workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.36.4/pack-v0.36.4-linux.tgz" | tar xz
          sudo mv pack /usr/local/bin/

      - name: Build container with Buildpacks
        run: |
          pack build ghcr.io/${{ github.repository_owner }}/my-app:latest --builder paketobuildpacks/builder:base

      - name: Push image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=kubeconfig.yaml set image deployment/my-app my-app=ghcr.io/${{ github.repository_owner }}/my-app:latest
          kubectl --kubeconfig=kubeconfig.yaml rollout status deployment/my-app
